### PR TITLE
Force linking against libgfortran

### PR DESCRIPTION
**Pull request by sawenzel**
Solves https://github.com/AliceO2Group/AliceO2/issues/314.

@qgp : Do you approve? Is this general enough?

### CODE REVIEW

**Comment by qgp** [comment]
Hi @sawenzel,

what's the reason of not placing this in the if-block checking for the use of gfortran as fortran compiler?

Cheers,
   Jochen

**Comment by sawenzel** [comment]
No particular reason. @mfasDa : Can you improve the PR as suggested?

**Comment by mfasDa** [comment]
Hi @qgp, Hi @sawenzel,

No particular reason either. How about with the second patch?

Cheers

Markus

**Comment by qgp** [comment]
Hi @mfasDa, @sawenzel,

looks ok to me. One more question: Do we understand why this is needed for some people but not for others (always macOS)? I will now merge this into the alipwgmm fork where we are staging the changes for the next release of the generators (and from where we are running the tests).

Cheers,
   Jochen

**Comment by mfasDa** [comment]
Hi @qgp,

Not clear to me either where the problem on macOS as on my Ubuntu system it builds without the patch. Maybe it is connected to the fortran compiler. I can tell you my setup for which the linking failed:

macOS Sierra 10.12.4
XCode 8.3.1
gfortran 6.3.0 from homebrew

Cheers

Markus

**Comment by mfasDa** [comment]
Any comment why the request has been closed without merging?

**Comment by qgp** [comment]
As mentioned above, the changes are merged into the alipwgmm fork:
https://github.com/alipwgmm/pythia6/tree/alice/428
where we are staging and testing the changes prior to merging to alisw and deploying to cvmfs.

I could not change the target of the pull request, that's why github does not show it as merged here, sorry for the confusion.

**Pull request closed without merging**
